// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jxmtnspicjpbvphlgzlz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4bXRuc3BpY2pwYnZwaGxnemx6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk2MTkyMDksImV4cCI6MjA5NTE5NTIwOX0._g2XRJRDnWnX3c9SnX1CVW2GnBVlEAN_BC9LnzTW8L8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});